---
title: "Bond Yields"
documentclass: elsarticle
Thesis_FP: no
output:
  pdf_document:
    keep_tex: yes
    template: Tex/TexDefault.txt
    fig_width: null
    fig_height: 3.5
  html_document:
    df_print: paged
Author1: Ronan Morris
Ref1: Stellenbosch University
Email1: 22876634
BottomRFooter: \footnotesize Page \thepage
addtoprule: yes
addfootrule: yes
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: yes
linenumbers: no
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: yes
toc: no
numbersections: yes
fontsize: 11pt
linestretch: 1.2
link-citations: yes
AddTitle: yes
---

```{r include=FALSE, warning=FALSE}

rm(list = ls())

gc()

###

library(tidyverse)

```

# Required Packages:

* tidyverse

# Loading and Editing Data sets

```{r}

  # 2 year Global Bonds.

Global_2yr <- readRDS("data/BondYields_2Y.rds") %>%
 
     mutate(Name = gsub("_2yr", "", Name)) %>% 
    
     filter(date <= "2022-03-31") # last available date in SA_2Yr

  # 10 year Global bonds.

Global_10yr <- readRDS("data/BondYields_10Y.rds") %>% 
    
    mutate(Name = gsub("_10Yr", "", Name)) %>% 
    
    filter(Name %in% Global_2yr$Name) %>% # Same bonds only
    
    filter(date <= "2022-03-31")

  # 2 year South African (SA) bonds. 

SA_2yr <- readRDS("data/BondYields_2Y_SA.rds") %>% 
    
    filter(date >= first(Global_10yr$date))

  # 10 Year SA bonds.

SA_10yr <- readRDS("data/BondYields_10Y_SA.rds") %>% 
    
    filter(date >= first(Global_10yr$date) & date <= "2022-03-31")

# the data sets all now start at the same date, and the global sets include the same bonds. 

# At this point it is clear that we have COVID-19 Data. Perhaps we can do a sort of crisis bond yield analysis? 

```

```{r}



```

